---
title: "Homework 3"
author: "Nathan Bick"
date: '2022-09-24'
output: pdf_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Problem 1

Let 

$$A = \begin{pmatrix} 
3 & -1 & 1 \\
0 & 2 & 1 \\
-1 & 1 & 4 
\end{pmatrix}, \ b = \begin{pmatrix} -1 \\ 0 \\ 1\end{pmatrix}$$

(a) Use the $LU$ factorization to express $A=LU$ where $L$ is a lower triangular and $U$ is an upper triangular matrix.

To solve this, we choose matrices $L_i$ that represent elementary operations lower triangular matrixcs to convert A to an upper triangular matrix, as in $L_{n-1} ... L_1A=U$.  

We first select $L_1$ as follow:

$$\begin{pmatrix} 
1 & 0 & 0 \\
0 & 1 & 0 \\
1/3 & 0 & 1 
\end{pmatrix}\begin{pmatrix} 
3 & -1 & 1 \\
0 & 2 & 1 \\
-1 & 1 & 4 
\end{pmatrix}=\begin{pmatrix} 
3 & -1 & 1 \\
0 & 2 & 1 \\
0 & 2/3 & 13/3
\end{pmatrix}$$

Then we select $L_2$ as follow:

$$\begin{pmatrix} 
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & -1/3 & 1 
\end{pmatrix}\begin{pmatrix} 
3 & -1 & 1 \\
0 & 2 & 1 \\
0 & 2/3 & 13/3
\end{pmatrix}=\begin{pmatrix} 
3 & -1 & 1 \\
0 & 2 & 1 \\
0 & 0 & 4 
\end{pmatrix}$$

We know that to find L we use $L=(L_2L_1)^{-1}=L_1^{-1}L_2^{-1}$

$$L = \begin{pmatrix} 
1 & 0 & 0 \\
0 & 1 & 0 \\
1/3 & 0 & 1 
\end{pmatrix}^{-1}\begin{pmatrix} 
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & -1/3 & 1 
\end{pmatrix}^{-1}=\begin{pmatrix} 
1 & 0 & 0 \\
0 & 1 & 0 \\
-1/3 & 0 & 1 
\end{pmatrix}\begin{pmatrix} 
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 1/3 & 1 
\end{pmatrix}=\begin{pmatrix} 
1 & 0 & 0 \\
0 & 1 & 0 \\
-1/3 & 1/3 & 1 
\end{pmatrix}, U = \begin{pmatrix} 
3 & -1 & 1 \\
0 & 2 & 1 \\
0 & 0 & 4 
\end{pmatrix}$$

Thus we arrive at our L and U matrices.

(b) Obtain the solution $x^*$ of the system$Ax=b$ using $LU$ factorization of $A$ together with forward and backward substitution.

We can solve a system using LU factorization by $L(Ux)=b \Leftrightarrow Ly=b$, and then solving via backward substitution. It is then easy to solve $Ux=y$ again via backward substitution.

First we solve 

$$\begin{pmatrix} 
1 & 0 & 0 \\
0 & 1 & 0 \\
-1/3 & 1/3 & 1 
\end{pmatrix}y=\begin{pmatrix} -1 \\ 0 \\ 1\end{pmatrix}$$ 

This gives $$y=\begin{pmatrix} -1 \\ 0 \\ 2/3\end{pmatrix}$$ 

Then we solve 

$$\begin{pmatrix} 
3 & -1 & 1 \\
0 & 2 & 1 \\
0 & 0 & 4 
\end{pmatrix}x=\begin{pmatrix} -1 \\ 0 \\ 2/3\end{pmatrix} \Rightarrow x=\begin{pmatrix} -5/12 \\ -1/12 \\ 1/6\end{pmatrix}$$ 

(c) Use Jacobi method twice, starting with $x^{(0)}=[1,1,0]^T$ to find an approximate solution. Report the error $\Vert x^{(k)} - x^*\Vert_{\infty}$, $k=1,2$.

The Jacobi method tries to solve using $x^{(k)}=x^{(k-1)} + D^{-1}(b-Ax^{(k-1)})$, where D is a diagonal matrix and is arrived at using $A=L+U+D$, where L and U are lower and upper triangular matrices, respectively. 

We know that $$D=\begin{pmatrix} 
1/3 & 0 & 0 \\
0 & 1/2 & 0 \\
0 & 0 & 1/4 
\end{pmatrix},\ x^{(0)}=\begin{pmatrix} 1 \\ 1 \\ 0\end{pmatrix}$$

We solve $$x^{(1)}= \begin{pmatrix} 1 \\ 1 \\ 0\end{pmatrix} + 
\begin{pmatrix} 
1/3 & 0 & 0 \\
0 & 1/2 & 0 \\
0 & 0 & 1/4 
\end{pmatrix}\left(\begin{pmatrix} -1 \\ 0 \\ 1\end{pmatrix} - \begin{pmatrix} 
3 & -1 & 1 \\
0 & 2 & 1 \\
-1 & 1 & 4 
\end{pmatrix}\begin{pmatrix} 1 \\ 1 \\ 0\end{pmatrix}\right)$$

$$x^{(1)}= \begin{pmatrix} 1 \\ 1 \\ 0\end{pmatrix} + 
\begin{pmatrix} 
1/3 & 0 & 0 \\
0 & 1/2 & 0 \\
0 & 0 & 1/4 
\end{pmatrix}\left(\begin{pmatrix} -1 \\ 0 \\ 1\end{pmatrix} - \begin{pmatrix} 2 \\ 2 \\ 0\end{pmatrix}\right)$$


$$x^{(1)}= \begin{pmatrix} 1 \\ 1 \\ 0\end{pmatrix} + 
\begin{pmatrix} 
1/3 & 0 & 0 \\
0 & 1/2 & 0 \\
0 & 0 & 1/4 
\end{pmatrix}\left(\begin{pmatrix} -3 \\ -2 \\ 1\end{pmatrix} \right) = \begin{pmatrix} 1 \\ 1 \\ 0\end{pmatrix} + \begin{pmatrix} -1 \\ -1 \\ 1/4\end{pmatrix}=\begin{pmatrix} 0 \\ 0 \\ 1/4\end{pmatrix}$$

For the second iterate we repeat
$$x^{(1)}= \begin{pmatrix} 0 \\ 0 \\ 1/4\end{pmatrix} + 
\begin{pmatrix} 
1/3 & 0 & 0 \\
0 & 1/2 & 0 \\
0 & 0 & 1/4 
\end{pmatrix}\left(\begin{pmatrix} -1 \\ 0 \\ 1\end{pmatrix} - \begin{pmatrix} 
3 & -1 & 1 \\
0 & 2 & 1 \\
-1 & 1 & 4 
\end{pmatrix}\begin{pmatrix} 0 \\ 0 \\ 1/4\end{pmatrix}\right)$$
$$x^{(1)}= \begin{pmatrix} 0 \\ 0 \\ 1/4\end{pmatrix} + 
\begin{pmatrix} 
1/3 & 0 & 0 \\
0 & 1/2 & 0 \\
0 & 0 & 1/4 
\end{pmatrix}\left(\begin{pmatrix} -1 \\ 0 \\ 1\end{pmatrix} - \begin{pmatrix} 1/4 \\ 1/4 \\ 1\end{pmatrix}\right)$$
$$x^{(1)}= \begin{pmatrix} 0 \\ 0 \\ 1/4\end{pmatrix} + 
\begin{pmatrix} 
1/3 & 0 & 0 \\
0 & 1/2 & 0 \\
0 & 0 & 1/4 
\end{pmatrix}\left(\begin{pmatrix} -5/4 \\ -1/4 \\ 0\end{pmatrix} \right)=\begin{pmatrix} 0 \\ 0 \\ 1/4\end{pmatrix} + \begin{pmatrix} -5/12 \\ -1/8 \\ 0\end{pmatrix}=\begin{pmatrix} -5/12 \\ -1/8 \\ 1/4\end{pmatrix}$$

This is approaching the correct solution.

(d) Write code for the Gauss-Siedel method, and apply it to find the solution of the system $Ax=b$ with $10^{-5}$ digits of accuracy. That is $\Vert x^k - x^* \Vert \leq 10^{-5}$ where $x^*$ is the solution of the system $x^* = A^{-1}b$ and $x^k$ is the $k$th iterate of Gauss-Seidel. 


The formula for Gauss-Seidel is given as $Dx^{(k+1)}=-Lx^{(k+1)}-Ux^{(k)} + b, k = 0,1,2,...$ and for $n=3$ we have the following clear form:

$$a_{11}x_1^{(k+1)} = -a_{12}x_2^{(k)}-a_{13}x_3^{(k)} + b_1$$
$$a_{22}x_2^{(k+1)} = -a_{21}x_1^{(k)}-a_{23}x_3^{(k)} + b_2$$
$$a_{33}x_3^{(k+1)} = -a_{31}x_1^{(k)}-a_{32}x_2^{(k)} + b_3$$

So we implement the above in a functoin and then call it iteratively. 

```{python}
import math

# function to do Gauss Seidel
def gauss_seidel(a, x ,b):
    #Finding length of a, here it's 3       
    n = len(a)                   
    # for loop for 3 times as to calculate x, y , z
    for j in range(0, n):        
        # temp variable d to store b[j]
        d = b[j]                  
          
        # to calculate  xi, yi, zi
        for i in range(0, n):     
            if(j != i):
                d-=a[j][i] * x[i]
        x[j] = d / a[j][j]
    return x  

  
```

We have defined the function, so now we apply it to our data. 
  
```{python}  
x_star = [-5/12,-1/12,1/6]
x = [1, 1, 0]                        
a = [[3, -1, 1],[0, 2, 1],[-1, 1, 4]]
b = [-1,0,1]

  
#loop i times
for i in range(0, 10):            
    x = gauss_seidel(a, x, b)
    print(x)  


```

We see that the results are similar to that of the Jacobi method, which is also similar to the direct solution. 


